name: ailmanki
favicon: null
layout_spectrum: 0.6787682140711695
typography_spectrum: 0.24398711789399385
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.015935512725263834
  lightness: 0.28820617869496346
  saturation: 0.11965348245576024
  rhythmicContrast: 0.26359157147817314
purpose: []
